[2023-03-20 15:35:42,143] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v4.2.read_and_load_business manual__2023-03-20T15:35:27.529831+00:00 [queued]>
[2023-03-20 15:35:42,185] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v4.2.read_and_load_business manual__2023-03-20T15:35:27.529831+00:00 [queued]>
[2023-03-20 15:35:42,186] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 15:35:42,187] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-03-20 15:35:42,187] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 15:35:42,225] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): read_and_load_business> on 2023-03-20 15:35:27.529831+00:00
[2023-03-20 15:35:42,230] {standard_task_runner.py:52} INFO - Started process 11362 to run task
[2023-03-20 15:35:42,237] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'to_posgrest_v4.2', 'read_and_load_business', 'manual__2023-03-20T15:35:27.529831+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/to_postgresql.py', '--cfg-path', '/tmp/tmp9d0bgsdm', '--error-file', '/tmp/tmpeayuc_i4']
[2023-03-20 15:35:42,239] {standard_task_runner.py:77} INFO - Job 58: Subtask read_and_load_business
[2023-03-20 15:35:42,561] {logging_mixin.py:109} INFO - Running <TaskInstance: to_posgrest_v4.2.read_and_load_business manual__2023-03-20T15:35:27.529831+00:00 [running]> on host 0b4cdb459521
[2023-03-20 15:35:42,914] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sakabuana31
AIRFLOW_CTX_DAG_ID=to_posgrest_v4.2
AIRFLOW_CTX_TASK_ID=read_and_load_business
AIRFLOW_CTX_EXECUTION_DATE=2023-03-20T15:35:27.529831+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-20T15:35:27.529831+00:00
[2023-03-20 15:35:42,997] {base.py:79} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: final, Login: ***, Password: ***, extra: {}
[2023-03-20 15:35:43,082] {dbapi.py:225} INFO - Running statement: 
            CREATE TEMPORARY TABLE temp_business (
                business_id text PRIMARY KEY,
                name text,
                address text,
                city text,
                state text,
                postal_code text,
                latitude float,
                longitude float,
                stars float,
                review_count int,
                is_open int,
                attributes text,
                categories text,
                hours text
            );

            COPY temp_business FROM '/opt/***/data/output-csv/business_restaurant.csv' DELIMITER ',' CSV HEADER;
            INSERT INTO business (business_id, name, address, city, state, postal_code, latitude, stars, review_count, is_open, attributes, categories, hours)
            SELECT business_id, name, address, city, state, postal_code, latitude, stars, review_count, is_open, attributes, categories, hours
            FROM temp_business
            ON CONFLICT (business_id) DO NOTHING;
        , parameters: None
[2023-03-20 15:35:44,141] {dbapi.py:233} INFO - Rows affected: 0
[2023-03-20 15:35:44,257] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=to_posgrest_v4.2, task_id=read_and_load_business, execution_date=20230320T153527, start_date=20230320T153542, end_date=20230320T153544
[2023-03-20 15:35:44,346] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-20 15:35:44,597] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
