[2023-03-20 16:51:55,142] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v4.6.create_postgres_table_business manual__2023-03-20T16:51:43.761619+00:00 [queued]>
[2023-03-20 16:51:55,179] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v4.6.create_postgres_table_business manual__2023-03-20T16:51:43.761619+00:00 [queued]>
[2023-03-20 16:51:55,180] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 16:51:55,180] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-03-20 16:51:55,181] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 16:51:55,220] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): create_postgres_table_business> on 2023-03-20 16:51:43.761619+00:00
[2023-03-20 16:51:55,224] {standard_task_runner.py:52} INFO - Started process 15679 to run task
[2023-03-20 16:51:55,231] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'to_posgrest_v4.6', 'create_postgres_table_business', 'manual__2023-03-20T16:51:43.761619+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/to_postgresql.py', '--cfg-path', '/tmp/tmp6jibs8tw', '--error-file', '/tmp/tmpycqidqq6']
[2023-03-20 16:51:55,233] {standard_task_runner.py:77} INFO - Job 129: Subtask create_postgres_table_business
[2023-03-20 16:51:55,539] {logging_mixin.py:109} INFO - Running <TaskInstance: to_posgrest_v4.6.create_postgres_table_business manual__2023-03-20T16:51:43.761619+00:00 [running]> on host 0b4cdb459521
[2023-03-20 16:51:55,855] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sakabuana31
AIRFLOW_CTX_DAG_ID=to_posgrest_v4.6
AIRFLOW_CTX_TASK_ID=create_postgres_table_business
AIRFLOW_CTX_EXECUTION_DATE=2023-03-20T16:51:43.761619+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-20T16:51:43.761619+00:00
[2023-03-20 16:51:55,935] {base.py:79} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: final, Login: ***, Password: ***, extra: {}
[2023-03-20 16:51:56,010] {dbapi.py:225} INFO - Running statement: 
            create table if not exists business (
                business_id text PRIMARY KEY,
                name text,
                address text,
                city text,
                state text,
                postal_code text,
                latitude float,
                longitude float,
                stars float,
                review_count int,
                is_open int,
                attributes text,
                categories text,
                hours text
            ) 
        , parameters: None
[2023-03-20 16:51:56,015] {postgres.py:71} INFO - NOTICE:  relation "business" already exists, skipping

[2023-03-20 16:51:56,108] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=to_posgrest_v4.6, task_id=create_postgres_table_business, execution_date=20230320T165143, start_date=20230320T165155, end_date=20230320T165156
[2023-03-20 16:51:56,192] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-20 16:51:56,433] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
