[2023-03-20 16:52:06,945] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v4.6.create_postgres_table_checkin manual__2023-03-20T16:51:43.761619+00:00 [queued]>
[2023-03-20 16:52:06,983] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v4.6.create_postgres_table_checkin manual__2023-03-20T16:51:43.761619+00:00 [queued]>
[2023-03-20 16:52:06,984] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 16:52:06,985] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-03-20 16:52:06,986] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 16:52:07,025] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): create_postgres_table_checkin> on 2023-03-20 16:51:43.761619+00:00
[2023-03-20 16:52:07,029] {standard_task_runner.py:52} INFO - Started process 15701 to run task
[2023-03-20 16:52:07,036] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'to_posgrest_v4.6', 'create_postgres_table_checkin', 'manual__2023-03-20T16:51:43.761619+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/to_postgresql.py', '--cfg-path', '/tmp/tmpzxckqvrh', '--error-file', '/tmp/tmp842023bw']
[2023-03-20 16:52:07,039] {standard_task_runner.py:77} INFO - Job 133: Subtask create_postgres_table_checkin
[2023-03-20 16:52:07,355] {logging_mixin.py:109} INFO - Running <TaskInstance: to_posgrest_v4.6.create_postgres_table_checkin manual__2023-03-20T16:51:43.761619+00:00 [running]> on host 0b4cdb459521
[2023-03-20 16:52:07,685] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sakabuana31
AIRFLOW_CTX_DAG_ID=to_posgrest_v4.6
AIRFLOW_CTX_TASK_ID=create_postgres_table_checkin
AIRFLOW_CTX_EXECUTION_DATE=2023-03-20T16:51:43.761619+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-20T16:51:43.761619+00:00
[2023-03-20 16:52:07,791] {base.py:79} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: final, Login: ***, Password: ***, extra: {}
[2023-03-20 16:52:07,873] {dbapi.py:225} INFO - Running statement: 
            create table if not exists checkin (
                business_id text,
                date_values date PRIMARY KEY
            ) 
        , parameters: None
[2023-03-20 16:52:07,878] {postgres.py:71} INFO - NOTICE:  relation "checkin" already exists, skipping

[2023-03-20 16:52:07,974] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=to_posgrest_v4.6, task_id=create_postgres_table_checkin, execution_date=20230320T165143, start_date=20230320T165206, end_date=20230320T165207
[2023-03-20 16:52:08,036] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-20 16:52:08,291] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
