[2023-03-20 18:16:14,518] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v4.7.create_postgres_table_checkin manual__2023-03-20T18:15:50.093337+00:00 [queued]>
[2023-03-20 18:16:14,557] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v4.7.create_postgres_table_checkin manual__2023-03-20T18:15:50.093337+00:00 [queued]>
[2023-03-20 18:16:14,558] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 18:16:14,559] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-03-20 18:16:14,559] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 18:16:14,597] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): create_postgres_table_checkin> on 2023-03-20 18:15:50.093337+00:00
[2023-03-20 18:16:14,604] {standard_task_runner.py:52} INFO - Started process 20280 to run task
[2023-03-20 18:16:14,611] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'to_posgrest_v4.7', 'create_postgres_table_checkin', 'manual__2023-03-20T18:15:50.093337+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/to_postgresql.py', '--cfg-path', '/tmp/tmpk68_1c50', '--error-file', '/tmp/tmpv17qa2bc']
[2023-03-20 18:16:14,613] {standard_task_runner.py:77} INFO - Job 164: Subtask create_postgres_table_checkin
[2023-03-20 18:16:14,917] {logging_mixin.py:109} INFO - Running <TaskInstance: to_posgrest_v4.7.create_postgres_table_checkin manual__2023-03-20T18:15:50.093337+00:00 [running]> on host 0b4cdb459521
[2023-03-20 18:16:15,256] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sakabuana31
AIRFLOW_CTX_DAG_ID=to_posgrest_v4.7
AIRFLOW_CTX_TASK_ID=create_postgres_table_checkin
AIRFLOW_CTX_EXECUTION_DATE=2023-03-20T18:15:50.093337+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-20T18:15:50.093337+00:00
[2023-03-20 18:16:15,347] {base.py:79} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: final, Login: ***, Password: ***, extra: {}
[2023-03-20 18:16:15,426] {dbapi.py:225} INFO - Running statement: 
            create table if not exists checkin (
                business_id text,
                date_values date PRIMARY KEY
            ) 
        , parameters: None
[2023-03-20 18:16:15,431] {postgres.py:71} INFO - NOTICE:  relation "checkin" already exists, skipping

[2023-03-20 18:16:15,522] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=to_posgrest_v4.7, task_id=create_postgres_table_checkin, execution_date=20230320T181550, start_date=20230320T181614, end_date=20230320T181615
[2023-03-20 18:16:15,574] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-20 18:16:15,809] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
