[2023-03-21 08:50:40,806] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: querry_postgres_v1.4.get_querry_postgres_table manual__2023-03-21T07:52:34.606843+00:00 [queued]>
[2023-03-21 08:50:40,843] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: querry_postgres_v1.4.get_querry_postgres_table manual__2023-03-21T07:52:34.606843+00:00 [queued]>
[2023-03-21 08:50:40,844] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-21 08:50:40,845] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-03-21 08:50:40,846] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-21 08:50:40,891] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): get_querry_postgres_table> on 2023-03-21 07:52:34.606843+00:00
[2023-03-21 08:50:40,898] {standard_task_runner.py:52} INFO - Started process 1923 to run task
[2023-03-21 08:50:40,909] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'querry_postgres_v1.4', 'get_querry_postgres_table', 'manual__2023-03-21T07:52:34.606843+00:00', '--job-id', '274', '--raw', '--subdir', 'DAGS_FOLDER/querry_posgresql.py', '--cfg-path', '/tmp/tmpcvfhg1wo', '--error-file', '/tmp/tmplarhb0t0']
[2023-03-21 08:50:40,912] {standard_task_runner.py:77} INFO - Job 274: Subtask get_querry_postgres_table
[2023-03-21 08:50:41,251] {logging_mixin.py:109} INFO - Running <TaskInstance: querry_postgres_v1.4.get_querry_postgres_table manual__2023-03-21T07:52:34.606843+00:00 [running]> on host 0b4cdb459521
[2023-03-21 08:50:41,592] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sakabuana31
AIRFLOW_CTX_DAG_ID=querry_postgres_v1.4
AIRFLOW_CTX_TASK_ID=get_querry_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T07:52:34.606843+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-21T07:52:34.606843+00:00
[2023-03-21 08:50:41,673] {base.py:79} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: final, Login: ***, Password: ***, extra: {}
[2023-03-21 08:50:41,753] {dbapi.py:225} INFO - Running statement: 
            SELECT review.date_values, temperature.status_temp, precipitation.status_preci, review.business_id, business.name, review.stars, review.date_values
            FROM review
            LEFT JOIN precipitation ON (review.date_values = precipitation.date)
            LEFT JOIN temperature ON (review.date_values = temperature.date)
            LEFT JOIN business ON (review.business_id = business.business_id)
            ORDER BY review.date_values
        , parameters: None
[2023-03-21 08:50:42,239] {dbapi.py:233} INFO - Rows affected: 72125
[2023-03-21 08:50:42,349] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=querry_postgres_v1.4, task_id=get_querry_postgres_table, execution_date=20230321T075234, start_date=20230321T085040, end_date=20230321T085042
[2023-03-21 08:50:42,443] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-21 08:50:42,693] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
