[2023-03-20 19:02:17,011] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v4.9.create_postgres_table_review manual__2023-03-20T19:01:39.369448+00:00 [queued]>
[2023-03-20 19:02:17,049] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v4.9.create_postgres_table_review manual__2023-03-20T19:01:39.369448+00:00 [queued]>
[2023-03-20 19:02:17,050] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 19:02:17,051] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-03-20 19:02:17,051] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 19:02:17,090] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): create_postgres_table_review> on 2023-03-20 19:01:39.369448+00:00
[2023-03-20 19:02:17,096] {standard_task_runner.py:52} INFO - Started process 23049 to run task
[2023-03-20 19:02:17,103] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'to_posgrest_v4.9', 'create_postgres_table_review', 'manual__2023-03-20T19:01:39.369448+00:00', '--job-id', '243', '--raw', '--subdir', 'DAGS_FOLDER/to_postgresql.py', '--cfg-path', '/tmp/tmpz9c6k2um', '--error-file', '/tmp/tmpet9ao_cg']
[2023-03-20 19:02:17,106] {standard_task_runner.py:77} INFO - Job 243: Subtask create_postgres_table_review
[2023-03-20 19:02:17,402] {logging_mixin.py:109} INFO - Running <TaskInstance: to_posgrest_v4.9.create_postgres_table_review manual__2023-03-20T19:01:39.369448+00:00 [running]> on host 0b4cdb459521
[2023-03-20 19:02:17,718] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sakabuana31
AIRFLOW_CTX_DAG_ID=to_posgrest_v4.9
AIRFLOW_CTX_TASK_ID=create_postgres_table_review
AIRFLOW_CTX_EXECUTION_DATE=2023-03-20T19:01:39.369448+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-20T19:01:39.369448+00:00
[2023-03-20 19:02:17,796] {base.py:79} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: final, Login: ***, Password: ***, extra: {}
[2023-03-20 19:02:17,873] {dbapi.py:225} INFO - Running statement: 
            create table if not exists review (
                review_id text PRIMARY KEY,
                user_id text,
                business_id text,
                stars int,
                useful int,
                funny int,
                cool int,
                text text,
                date_values date
            ) 
        , parameters: None
[2023-03-20 19:02:17,970] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=to_posgrest_v4.9, task_id=create_postgres_table_review, execution_date=20230320T190139, start_date=20230320T190217, end_date=20230320T190217
[2023-03-20 19:02:18,030] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-20 19:02:18,231] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
