[2023-03-20 15:38:58,893] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v4.2.create_postgres_table_user manual__2023-03-20T15:35:27.529831+00:00 [queued]>
[2023-03-20 15:38:58,936] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: to_posgrest_v4.2.create_postgres_table_user manual__2023-03-20T15:35:27.529831+00:00 [queued]>
[2023-03-20 15:38:58,937] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 15:38:58,937] {taskinstance.py:1239} INFO - Starting attempt 2 of 3
[2023-03-20 15:38:58,938] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 15:38:58,992] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): create_postgres_table_user> on 2023-03-20 15:35:27.529831+00:00
[2023-03-20 15:38:58,999] {standard_task_runner.py:52} INFO - Started process 11540 to run task
[2023-03-20 15:38:59,008] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'to_posgrest_v4.2', 'create_postgres_table_user', 'manual__2023-03-20T15:35:27.529831+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/to_postgresql.py', '--cfg-path', '/tmp/tmpc92g2isc', '--error-file', '/tmp/tmp1nenc0ug']
[2023-03-20 15:38:59,012] {standard_task_runner.py:77} INFO - Job 60: Subtask create_postgres_table_user
[2023-03-20 15:38:59,340] {logging_mixin.py:109} INFO - Running <TaskInstance: to_posgrest_v4.2.create_postgres_table_user manual__2023-03-20T15:35:27.529831+00:00 [running]> on host 0b4cdb459521
[2023-03-20 15:38:59,690] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sakabuana31
AIRFLOW_CTX_DAG_ID=to_posgrest_v4.2
AIRFLOW_CTX_TASK_ID=create_postgres_table_user
AIRFLOW_CTX_EXECUTION_DATE=2023-03-20T15:35:27.529831+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-20T15:35:27.529831+00:00
[2023-03-20 15:38:59,771] {base.py:79} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: final, Login: ***, Password: ***, extra: {}
[2023-03-20 15:38:59,855] {dbapi.py:225} INFO - Running statement: 
            create table if not exists user1 (
                user_id text PRIMARY KEY,
                name text,
                review_count text,
                useful int,
                funny int,
                cool int,
                elite int,
                friends text,
                fans text,
                average_stars int,
                yelping_since_values date
            ) 
        , parameters: None
[2023-03-20 15:38:59,964] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=to_posgrest_v4.2, task_id=create_postgres_table_user, execution_date=20230320T153527, start_date=20230320T153858, end_date=20230320T153859
[2023-03-20 15:39:00,022] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-20 15:39:00,234] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
